'use client';

import { SessionProvider, useSession } from "next-auth/react";
import { LoadingProvider } from "./utils/loadingOverlay";
import "./globals.css";
import { useEffect } from "react";
import { signOut } from "next-auth/react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function SessionErrorHandler({ children }: { children: React.ReactNode }) {
  const { data: session } = useSession();

  useEffect(() => {
    if (session?.error === "RefreshAccessTokenError") {
      console.log("Session expired, logging out...");
      signOut();
    }
  }, [session?.error]);

  return <>{children}</>;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <SessionProvider>
          <SessionErrorHandler>
            <LoadingProvider>{children}</LoadingProvider>
          </SessionErrorHandler>
        </SessionProvider>
      </body>
    </html>
  );
}
