import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "./Sidebar";
import { Header } from "./Header";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header />
        <div className="flex w-full h-[calc(100vh)] pt-[64px] overflow-y-auto">
          <Sidebar />
          <div className="flex-1 h-full overflow-y-auto scrollbar-hover">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
